services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - '10001:3000'
    environment:
      - JWT_SECRET=${JWT_SECRET}
